CREATE TABLE CONTATOS (
	PK_COD_CONTATOS INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	TEL_RES VARCHAR(18),
	TEL_CEL VARCHAR(18),
	DATA_NAS DATETIME,
	ENDERECO VARCHAR(50),
	CIDADE VARCHAR (30),

	CONSTRAINT PK_CONTATOS PRIMARY KEY (PK_COD_CONTATOS)

	)

CREATE TABLE COMPROMISSOS (
	PK_COD_COMPROMISSOS INT NOT NULL,
	DATA DATETIME,
	HORARIO VARCHAR(10),
	LLOCAL VARCHAR(50),
	DESCRICAO VARCHAR(100),

	CONSTRAINT PK_COMPROMISSOS PRIMARY KEY (PK_COD_COMPROMISSOS)

	)